### PR TITLE
Support form encoded parameters, required by Microsoft

### PR DESCRIPTION
**Pull request by philcowans**
I've made this change to allow me to authenticate against Microsoft 365 - basically it looks like MS require requests to the token endpoint to be POST requests, but with the parameters form encoded in the body rather than the JSON which is required for Google.

I haven't actually got this working end to end yet, but I have obtained an access token.

Hope it's useful!

Phil

### CODE REVIEW

**Comment by pdobsan** [comment]
> it looks like MS require requests to the token endpoint to be POST requests, but with the parameters form encoded in the body rather than the JSON which is required for Google.

Thank you for figuring this out!

> I haven't actually got this working end to end yet, but I have obtained an access token.

I wait until you completely succeed.

If you could also modify the `microsoft` entry in `services-template.yaml` reflecting how you have done it that would be great.

**Comment by philcowans** [comment]
Okay - this is now working end-to-end for me. The other problem I was facing was that the error message returned because I have no crontab was being picked up as part of the token by my mail client, so I've also added a guard to prevent that specific error being echoed back to the user.

I've also updated the README and the configuration example.

**Comment by pdobsan** [comment]
Merged.
Thank you!

**Comment by ArthurBorsboom** [comment]
Hi Phil,

I have noticed that you have managed to authenticate against MS365. I am having trouble authenticating, so I am trying to find a clue, see  #12 . I am suspecting MS365 + MFA being an issue.

The MS365 account you have used, does it have MFA enabled?

**Comment by philcowans** [comment]
Hi @ArthurBorsboom - yes I do have MFA enabled (using SMS), and that wasn't a problem for me.

It's also an organisation account (my work email), so one thing which was a bit of a gotcha was the need to click the 'Sign in options' button on the login screen. Typing the email into the first box doesn't work.

Screenshot 2022-10-12 at 06-34-44 Sign in to your account
Screenshot 2022-10-12 at 06-34-35 Sign in to your account

**Comment by ArthurBorsboom** [comment]
Hi Phil,

Thanks for clarifying the login process that you experience.
It is helpful for the following parts, since our accounts share several items.

- MFA is unlikely to be the cause
- An organizational account is unlikely to be the cause.

The login experience I see is a bit different than yours.
MS presents instantly the password login form, based on the email address provided on the CLI.

I will stop analyzing further on this thread, since I don't want to hijack this thread.
I will continue on the thread created by me (#12).

Thanks for your feedback.

**Comment by ArthurBorsboom** [comment]
Hi Phil,

Which browser are you using?

**Comment by philcowans** [comment]
I'm using Firefox.

Have you tried using a label which isn't an email address for the account, e.g. `mailctl authorize microsoft workemail`? You can enter the address later, and that forces you onto the generic flow.

**Comment by ArthurBorsboom** [comment]
> mailctl authorize microsoft workemail

This helped partially, but feels like the right way.

The MS form presented asks for the MS account.
It also gives the option [Sign in Options] asking for the domain, user, password and MFA.

After the MFA has been provided it ended with the following error.

2022-10-12-144947_825x450_scrot

I recall setting up the OAuth2 authentication for an IT support system and there I have used different endpoints.
I will try this in a moment as well.

**Comment by philcowans** [comment]
Yep, that definitely looks like it's outside of mailctl.

If you have time, when you're done it might be a good idea to add a few lines to the README explaining what you needed to do to get it working.

**Comment by pdobsan** [comment]
> Yep, that definitely looks like it's outside of mailctl.
> 
> If you have time, when you're done it might be a good idea to add a few lines to the README explaining what you needed to do to get it working.

Yes, but instead of the Readme put into the wiki. Please see #13

**Pull request merged**
